
# source
if [ -d ~/.zprezto ]; then
    source ~/.zprezto/runcoms/zshrc
fi
source ~/_bin/dot-common/aliases.sh
source ~/_bin/dot-common/env-zsh.sh
source ~/_bin/dot-common/help-functions.sh

# init z - https://github.com/rupa/z
source ~/_bin/dot-common/z.sh

# additional zsh auto-completions from homebrew
fpath=(/usr/local/share/zsh-completions $fpath)
